/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    Confirm: typeof import('./src/components/Confirm.vue')['default']
    DlgObjectSelect: typeof import('./src/components/DlgObjectSelect.vue')['default']
    DyGraph: typeof import('./src/components/DyGraph.vue')['default']
    HistoryEditor: typeof import('./src/components/HistoryEditor.vue')['default']
    Locations: typeof import('./src/components/Locations.vue')['default']
    Splitter: typeof import('./src/components/Splitter.vue')['default']
    StructView: typeof import('./src/components/StructView.vue')['default']
    TextFieldNullableNumber: typeof import('./src/components/TextFieldNullableNumber.vue')['default']
    TreeView: typeof import('./src/components/TreeView.vue')['default']
  }
}
